FROM phusion/baseimage:0.9.17

# Regenerate SSH host keys. baseimage-docker does not contain any
# RUN /usr/bin/ssh-keygen -A
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh

# enable SSH service
RUN rm -f /etc/service/sshd/down


# The insecure key is from https://raw.githubusercontent.com/phusion/baseimage-docker/master/image/services/sshd/keys/insecure_key
RUN /usr/sbin/enable_insecure_key


RUN curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
RUN apt-get -y install rabbitmq-server
RUN /etc/init.d/rabbitmq-server start
RUN rabbitmq-plugins enable rabbitmq_management
RUN /etc/init.d/rabbitmq-server restart


# So that Vagrant can detect the machine
EXPOSE 22

EXPOSE 5672
EXPOSE 15672


#RUN service ssh start
CMD /bin/bash
